### ISSUE TITLE
Question about addItems()

### ISSUE THREAD

**Issue by colinricardo** [DoubleSymmetry/SwiftAudioEx#10]
In `QueueManager.swift`, line 96, you have: 

```
    public func addItems(_ items: [T], at index: Int) throws {
        guard index >= 0 && _items.count > index else {
            throw APError.QueueError.invalidIndex(index: index, message: "Index for addition has to be positive and smaller than the count of current items (\(_items.count))")
        }
        
        _items.insert(contentsOf: items, at: index)
        if (_currentIndex >= index) { _currentIndex = _currentIndex + items.count }
    }
```

Question: why is the guard not like: 

```
 guard index >= 0 && _items.count >= index else { // >= for both
```

If I understand correctly; the way it's set up now, `addItems(tracks, 0)` will fail when there's nothing in the queue, but `_items.insert(at :0)` would actually be perfectly valid, no?

**Comment by dcvz** [comment]
I think you might be right! @colinricardo feel like making a PR and covering this issue with tests?

**Comment by dcvz** [comment]
Fixed in: https://github.com/DoubleSymmetry/SwiftAudioEx/commit/a9f831a2584a405a94720dc81d6ca855df43ca4d!
