### ISSUE TITLE
Library is too opinionated about track repeat functionality

### ISSUE THREAD

**Issue by mmmoussa** [DoubleSymmetry/SwiftAudioEx#12]
**Describe the bug**
https://github.com/DoubleSymmetry/SwiftAudioEx/commit/7b8a4f318db595aa1b2919407c02da0a1facc160 added logic designed to block a smooth playback experience with repeating tracks. Potentially there's a product experience where this is desirable, but for others it attempts to block core parts of the product experience. In my product experience, users should be allowed to setup a queue with the current track on loop, and whenever they are ready to move on to the next or previous track, they can skip to next/previous, with that track set to play right away without any interference and with the repeat mode still on loop. At present, this is not what happens.

**To Reproduce**
Setup a queue with track repeat mode and try skipping to the next track. New track does not play.

**Expected behavior**
Next track is loaded and starts playing.

**Screenshots**
N/A

**Smartphone**
 - Device: All
 - OS: iOS 15.4
 - Version: 0.14.7

**Additional context**
It's worth noting that in RNTP, the Android behaviour is exactly as I had expected it to be (ie. it does not stop playback when skipping tracks in track repeat mode.

**Comment by dcvz** [comment]
thanks for raising this @mmmoussa -- we should definitely replicate the behaviour of most libraries.

**Comment by dcvz** [comment]
This has now been fixed in https://github.com/DoubleSymmetry/SwiftAudioEx/commit/cc3840d81e7e4068e2755cc5b633214ec98cb3ea and will go out in the next release!

**Comment by dcvz** [comment]
This out in version `0.15.0`!

**Comment by dcvz** [comment]
There's a branch underway that has the latest SwiftAudioEx: https://github.com/DoubleSymmetry/react-native-track-player/pull/1459
