### ISSUE TITLE
AirPlay is broken with live streaming audio

### ISSUE THREAD

**Issue by DennisdeWitNL** [doublesymmetry/SwiftAudioEx#13]
**Describe the bug**
When playing live streaming audio such as radio stations, it doesn't switch properly. When first initiating the session with an AirPlay device and then opening the app, it works fine. But once clicking back to 'iPhone', the stream stops again.

**To Reproduce**

1. Open the example app and change the url to a live medium
2. Play the stream;
3. Press the power button and choose AirPlay. Choose for your HomePod Mini
4. The HomePod Mini is now connected, there is just no audio going through it. However, the HomePod Mini shows a white hue, so it is connected.

**Expected behavior**
Logical switching between iPhone and AirPlay devices, the way it works fine with mp3 files.

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
macOS 12.3

**Smartphone (please complete the following information):**
iOS 15.4, iPhone 13 Pro Max

**Additional context**
This is the issue as described [here](https://github.com/DoubleSymmetry/react-native-track-player/issues/1408)

I am just not sure if David is the only developer of SwiftAudioEx or some other developers contribute to this project too.

**Comment by jspizziri** [comment]
@DennisdeWitNL , came here from the corresponding RNTP issue. I've contributed to this project before and I know David is a super busy guy, but I'm sure he could provide some high-level oversight if you were willing to take a crack at solving this issue. Are you able to give it a shot?

**Comment by DennisdeWitNL** [comment]
This problem has been solved by Apple on iOS 15.5 beta 4.
