### ISSUE TITLE
`.add`, `.load`, `.play` and `AudioPlayerState` have no way to show loading errors from expired S3 link

### ISSUE THREAD

**Issue by kevnk** [doublesymmetry/SwiftAudioEx#24]
**Describe the bug**
I have a URL to an expired amazon S3 item that won't play, but nothing (that I can see at least) in the adding, loading, playing methods or `AudioPlayerState` that indicates that it can't load the audio properly from that expired URL.

**To Reproduce**
I'm guessing it may be because the URL itself has a 200 response, but not one that would load an audio file. Here's an example of [a link](https://d1iqfqur1f28d9.cloudfront.net/656/tracks/51_Chapter%2048.wav?Expires=1661953596&Signature=avsYXZWYlZ4L0WLKSHwAlAQPK05rBXV1lUoySwVev~8UAaisPdxBNoX9na54beMs7C7WwaX~XWAbKk-2uSmbIMncLSDBsQH9znLyLKZ7aX~5-tFzGROzXxGpAYDlmK91zx89fjnjwrb5vnu5YRxjKzZPypP0GDHpi80NmO1xWZck0vAnEhJpH9szWApkKz5rtqXJvh-E2hZbiZu3Vpj5VjZ22cYAxRf6m5Pu-XHDJZLhgygKFDbwNZB4iDc6EMCscg2FpQvctnteAuTS34XCgX8kHw8h-N3d01VwpUXi6Yb-eL~pzebS-RSCXVutwD4PqrU0CMR9bQ18sd97eET7cw__&Key-Pair-Id=APKAIYVWHLHWXUL4UZNQ) that once worked, but has since expired.

**Expected behavior**
In the adding or loading of an AudioItem with a URL that won't resolve an audio file, I would expect some error to be thrown

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone11
 - OS: iOS13.4.1 (I think)
 - SwiftAudioEx Version 0.15.2

**Comment by jspizziri** [comment]
@kevnk what is the actual behavior you're seeing?

Additionally, it's not a `200` response, it's a `403`.

**Comment by kevnk** [comment]
Oh good know...

The actual behavior I'm seeing is when trying to play, ie. `audioPlayer.play()` it just doesn't do anything. The code keeps running as normal, but there's no audio playing and there's no error thrown.

I'd have to check, but there may be a state change to "loading" that just never resolves...

**Comment by puckey** [comment]
Listening for a fail event should work – just added a test for this to a broad pr I am working on: https://github.com/doublesymmetry/SwiftAudioEx/pull/28/commits/91a80cdd2671ef128e6b88cf710192d0be44e0ac#diff-88a9fc27aac2e762df556c38f91b377449988a105d8845a48254a8bba825b3ecR303

**Comment by jspizziri** [comment]
We are in fact [listening to that event](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L32) and firing the `PlaybackError` event when it happens. 

@kevnk are you listening to that event?

**Comment by jspizziri** [comment]
@kevnk I just tested this and the event does fire as I'd expect. See a sample log below for an attempt to play the file you documented above:

```
 LOG  Event.PlaybackError {"error": "You do not have permission to access the requested resource."}
 ```

**Comment by jspizziri** [comment]
@dcvz I just tested this in RNTP and puckey wrote a test for it. This is in fact working via an event as I'd expect. I think this issue should be closed.

@kevnk please look at the event that puckey mentioned.

**Comment by kevnk** [comment]
I was only listening to the `stateChange` event and was expecting for there to be some.kind of error state... But now I see how I can use the `fail` event. THANKS!

**Comment by jspizziri** [comment]
@kevnk can you close this issue please?
