### ISSUE TITLE
Specs satisfying the `SwiftAudioEx (~> 0.14.2)` dependency were found, but they required a higher minimum deployment

### ISSUE THREAD

**Issue by jiangxiaoqiang** [DoubleSymmetry/SwiftAudioEx#7]
what is the minimal target deployment version should I use? I am use the 10.0 right now from the official document of github.

**Comment by dcvz** [comment]
Minimum deployment target is iOS 11 in this release: https://github.com/DoubleSymmetry/SwiftAudioEx/releases/tag/0.14.0

**Comment by dcvz** [comment]
Documentation was updated!
