### ISSUE TITLE
Crash in `AVPlayerItemObserver` with `playbackLikelyToKeepUp` not registered as observer

### ISSUE THREAD

**Issue by fivecar** [doublesymmetry/SwiftAudioEx#78]
**Describe the bug**
Crashed with this:
```
Cannot remove an observer <SwiftAudioEx.AVPlayerItemObserver 0x30309bf00> for the key path
"playbackLikelyToKeepUp" from <AVPlayerItem 0x3027a8c90> because it is not registered as an observer.
```

**To Reproduce**
Interestingly, the user session only lasted 7 seconds before this crash. So I suspect this happens early in setup (I'm using RNTP), or perhaps shortly after, when a track is added.

**Smartphone (please complete the following information):**
Device And OS: iPhone SE 2nd Gen, iOS 17.4.1
Locale: sv-SE
Screen Size: 375x667

**Additional context**
Was using RNTP RC4.

**Comment by fivecar** [comment]
(as always, I'm happy to help contribute a fix if someone knows where to look, or what the root cause might be)

**Comment by bsneed** [comment]
@fivecar did this happen just once, or do you see it as a regular crash?

**Comment by fivecar** [comment]
@bsneed : haven't seen it much recently. Will ping back if I see it again.
