### ISSUE TITLE
could you please upload the lastest version 0.14.5 to the cocopods repo

### ISSUE THREAD

**Issue by jiangxiaoqiang** [DoubleSymmetry/SwiftAudioEx#8]
I could not fetch the version of 0.14.5 version from pod install.

**Comment by gbesler** [comment]
same here, any news?

**Comment by jr00n** [comment]
Yes please!
`[!] Unable to read the license file `LICENSE` for the spec `SwiftAudioEx (0.14.5)``

**Comment by dcvz** [comment]
We've had some more releases since then! This should be solved.

**Comment by terrysmith** [comment]
I'm getting the same issue [!] Unable to read the license file `LICENSE` for the spec `SwiftAudioEx (0.14.5)` How do I resolve it from cocoapods?

**Comment by dcvz** [comment]
This was fixed from 14.6+ @terrysmith it seems like you're on an older version.
Closing this now as its been fixed and verified.

**Comment by terrysmith** [comment]
Got it! Thanks.
________________________________
